### ISSUE TITLE
building the docker image stuck because of "country of origin for the keyboard" prompt

### ISSUE THREAD

**Issue by NiciSteck** [yv1es/MRMapper#5]
When building the docker image with `build_image.bat` the terminal got stuck at the `RUN apt install -y ros-noetic-rtabmap` command because there was a "country of origin for the keyboard" prompt that I could not interact with.
I solved the problem by using `RUN apt update \ && DEBIAN_FRONTEND=noninteractive apt install -y ros-noetic-rtabmap` in the dockerfile instead (as you did for the first RUN).
Im not sure if this behavior was just a me-problem but I thought I'd leave this issue for future reference.

**Comment by yv1es** [comment]
Thank you, it is not a you problem. `RUN apt update \ && DEBIAN_FRONTEND=noninteractive apt install -y` should be used in general to avoid these issues, I updated the Docker file.
